language: node_js
sudo: false
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "iojs"
  - "4"
  - "5"
  - "6"
after_success:
  - codeclimate-test-reporter < coverage/lcov.info
  - coveralls < coverage/lcov.info
