language: node_js
sudo: false
node_js:
  - "6"
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
after_success:
  - codeclimate-test-reporter < coverage/lcov.info
  - coveralls < coverage/lcov.info
