language: node_js
sudo: false
node_js:
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
after_success:
  - travis_retry codeclimate-test-reporter < coverage/lcov.info
  - travis_retry coveralls < coverage/lcov.info
