language: node_js
sudo: false
node_js:
  - lts/*
after_success:
  - travis_retry nyc report --reporter=text-lcov | codeclimate-test-reporter
  - travis_retry nyc report --reporter=text-lcov | coveralls
