language: node_js
node_js:
  - 12
  - 14
  - node
after_success:
  - travis_retry nyc report --reporter=text-lcov | codeclimate-test-reporter
  - travis_retry nyc report --reporter=text-lcov | coveralls
